@startuml
title A1.2: Diagrama de Actividades - Modificar Evento Existente

|#skyblue|Coordinación|
start
:Accede a "Gestión de Eventos";
:Selecciona un evento de la lista;
:Elige la opción "Modificar";

|#whitesmoke|Módulo administrativo|
:Presenta formulario con datos del evento;

|#skyblue|Coordinación|
:Edita la información necesaria;
:Guarda los cambios;

|#whitesmoke|Módulo administrativo|
:Valida los datos actualizados;
:Actualiza el evento en la BD;
:Muestra mensaje de confirmación;
stop
@enduml