@startuml
title A2.1: Diagrama de Actividades - Crear Nueva Categoría

|#skyblue|Coordinación|
start
:Accede a "Gestión de Categorías";
:Selecciona "Crear Categoría";

|#whitesmoke|Módulo administrativo|
:Solicita nombre de la nueva categoría;

|#skyblue|Coordinación|
:Ingresa el nombre;
:Guarda la categoría;

|#whitesmoke|Módulo administrativo|
if (Nombre ya existe?) then (sí)
  :Muestra error de nombre duplicado;
else (no)
  :Guarda la nueva categoría;
  :Muestra mensaje de confirmación;
endif
stop
@enduml