@startuml
title A2.2: Diagrama de Actividades - Modificar Categoría

|#skyblue|Coordinación|
start
:Accede a "Gestión de Categorías";
:Selecciona una categoría de la lista;
:Elige "Modificar";

|#whitesmoke|Módulo administrativo|
:Permite editar el nombre;

|#skyblue|Coordinación|
:Edita el nombre y guarda;

|#whitesmoke|Módulo administrativo|
if (Nuevo nombre ya existe?) then (sí)
   :Muestra error de nombre duplicado;
else (no)
  :Actualiza el nombre de la categoría;
  :Muestra mensaje de confirmación;
endif
stop
@enduml