@startuml
title A4.2: Diagrama de Actividades - Modificar Información de Capacitador

|#skyblue|Coordinación|
start
:Accede a "Gestión de Capacitadores";
:Selecciona un capacitador y elige "Editar";

|#whitesmoke|Módulo administrativo|
:Muestra formulario con datos actuales;

|#skyblue|Coordinación|
:Actualiza la información y guarda;

|#whitesmoke|Módulo administrativo|
:Guarda los cambios y confirma;
stop
@enduml