@startuml
title A4.1: Diagrama de Actividades - Registrar Nuevo Capacitador

|#skyblue|Coordinación|
start
:Accede a "Gestión de Capacitadores";
:Selecciona "Registrar Capacitador";

|#whitesmoke|Módulo administrativo|
:Presenta formulario de registro;

|#skyblue|Coordinación|
:Completa información básica y profesional;
:Guarda el nuevo capacitador;

|#whitesmoke|Módulo administrativo|
:Valida datos y crea el registro;
:Muestra confirmación;
stop
@enduml