@startuml
title Diagrama de Actividades - Eliminar Evento Existente (CU-GE-004)

|#skyblue|Coordinadora de EC|
start
:Accede a "Gestión de Eventos";
:Selecciona un evento de la lista;
:Elige la opción "Eliminar";

|#whitesmoke|Módulo administrativo|
:Solicita confirmación para eliminar;

|#skyblue|Coordinadora de EC|
:Confirma la eliminación;

|#whitesmoke|Módulo administrativo|
if (Evento tiene inscripciones activas?) then (sí)
   :Muestra error: "No se puede eliminar,
   el evento tiene participantes";
else (no)
  :Elimina el evento de la BD;
  :Muestra mensaje de confirmación;
endif
stop
@enduml