@startuml CU-GE-009_Crear_Categoria
title Diagrama de Actividades - Crear Nueva Categoría (CU-GE-009)

|#skyblue|Coordinadora de EC|
start
:Inicia gestión de categorías;
:Solicita creación de categoría;

|#whitesmoke|Módulo administrativo|
:Solicita nombre de la nueva categoría;

|#skyblue|Coordinadora de EC|
:Proporciona nombre;
:Confirma registro de la categoría;

|#whitesmoke|Módulo administrativo|
if (¿Nombre ya existe?) then (sí)
  :Informa que el nombre está duplicado;
else (no)
  :Registra la nueva categoría;
  :Informa confirmación;
endif
stop
@enduml