@startuml CU-GE-004_Eliminar_Evento
title Diagrama de Actividades - Eliminar Evento Existente (CU-GE-004)

|#skyblue|Coordinadora de EC|
start
:Inicia gestión de eventos;
:Indica el evento objetivo;
:Solicita eliminación del evento;

|#whitesmoke|Módulo administrativo|
:Requiere confirmación de eliminación;

|#skyblue|Coordinadora de EC|
:Confirma la decisión;

|#whitesmoke|Módulo administrativo|
if (¿El evento tiene inscripciones activas?) then (sí)
   :Informa que no es posible eliminar por participantes activos;
else (no)
  :Registra la eliminación del evento;
  :Informa confirmación de eliminación;
endif
stop
@enduml