@startuml CU-GE-012_Eliminar_Categoria
title Diagrama de Actividades - Eliminar Categoría (CU-GE-012)

|#skyblue|Coordinadora de EC|
start
:Inicia gestión de categorías;
:Indica categoría objetivo;
:Solicita eliminación;

|#whitesmoke|Módulo administrativo|
:Requiere confirmación;

|#skyblue|Coordinadora de EC|
:Confirma la decisión;

|#whitesmoke|Módulo administrativo|
if (¿Categoría está en uso?) then (sí)
  :Informa que la categoría está en uso;
else (no)
  :Registra eliminación de la categoría;
  :Informa confirmación;
endif
stop
@enduml