@startuml CU-GE-005_Generar_Constancias
title Diagrama de Actividades - Generación de Constancias (CU-GE-005)

|#skyblue|Coordinadora de EC|
start
:Inicia proceso de constancias y reportes;
:Solicita generación de constancias;

|#whitesmoke|Módulo administrativo|
:Solicita especificar evento;

|#skyblue|Coordinadora de EC|
:Indica el evento objetivo;

|#whitesmoke|Módulo administrativo|
:Provee participantes elegibles
(que cumplieron los requisitos);

|#skyblue|Coordinadora de EC|
:Define participantes a incluir;
:Confirma generación de constancias;

|#whitesmoke|Módulo administrativo|
:Genera constancias con plantilla establecida;
:Habilita opciones para distribución (descarga/envío);

|#skyblue|Coordinadora de EC|
:Ejecuta la distribución definida;
stop
@enduml