@startuml CU-GE-011_Modificar_Categoria
title Diagrama de Actividades - Modificar Categoría (CU-GE-011)

|#skyblue|Coordinadora de EC|
start
:Inicia gestión de categorías;
:Indica categoría a modificar;
:Solicita modificación;

|#whitesmoke|Módulo administrativo|
:Provee información de la categoría;

|#skyblue|Coordinadora de EC|
:Actualiza el nombre y confirma;

|#whitesmoke|Módulo administrativo|
if (¿Nuevo nombre ya existe?) then (sí)
   :Informa nombre duplicado;
else (no)
  :Registra el nuevo nombre de la categoría;
  :Informa confirmación;
endif
stop
@enduml