@startuml CU-GE-006_Generar_Reportes
title Diagrama de Actividades - Generación de Reportes (CU-GE-006)

|#skyblue|Coordinación|
start
:Inicia proceso de constancias y reportes;
:Solicita generación de reporte de eventos;

|#whitesmoke|Módulo administrativo|
:Indica reportes disponibles
(ej. Lista de participantes, Ingresos);

|#skyblue|Coordinación|
:Define tipo de reporte y parámetros
(ej. evento, fechas);
:Confirma generación del reporte;

|#whitesmoke|Módulo administrativo|
:Procesa la información requerida;
:Genera el reporte (PDF, Excel);
:Habilita opción para distribución (descarga);

|#skyblue|Coordinación|
:Accede al reporte generado;
stop
@enduml