@startuml CU-GE-003_Modificar_Evento
title Diagrama de Actividades - Modificar Evento Existente (CU-GE-003)

|#skyblue|Coordinadora de EC|
start
:Inicia gestión de eventos;
:Indica evento a modificar;
:Solicita modificación;

|#whitesmoke|Módulo administrativo|
:Provee información actual del evento;

|#skyblue|Coordinadora de EC|
:Actualiza la información necesaria;
:Confirma los cambios;

|#whitesmoke|Módulo administrativo|
:Valida la información;
:Registra la actualización del evento;
:Informa confirmación;
stop
@enduml