@startuml CU-MU-002_Validacion_Documentos
title Diagrama de Actividades - Validación de Documentos (CU-MU-002)

|#skyblue|Coordinación|
start
:Inicia proceso de validaciones;
:Solicita validar documentación de usuario;

|#whitesmoke|Módulo administrativo|
:Provee usuarios con
documentos pendientes de validación;

|#skyblue|Coordinación|
:Determina documento a revisar;

|#whitesmoke|Módulo administrativo|
:Provee el documento para revisión;

|#skyblue|Coordinación|
:Revisa el documento;
if (¿Documento es válido?) then (Sí)
  :Registra documento como "Validado";
  |#whitesmoke|Módulo administrativo|
  :Actualiza el estado del documento;
  :Notifica al usuario según configuración;
else (No)
  :Registra documento como "No Válido";
  |#whitesmoke|Módulo administrativo|
  :Actualiza el estado del documento;
  :Solicita al usuario aportar un nuevo documento;
endif
stop
@enduml