@startuml CU-MU-003_Registrar_Capacitador
title Diagrama de Actividades - Registrar Nuevo Capacitador (CU-MU-003)

|#skyblue|Coordinadora de EC|
start
:Inicia gestión de capacitadores;
:Solicita registro de capacitador;

|#whitesmoke|Módulo administrativo|
:Solicita datos de registro;

|#skyblue|Coordinadora de EC|
:Proporciona información básica y profesional;
:Confirma registro;

|#whitesmoke|Módulo administrativo|
:Valida datos y crea el registro;
:Informa confirmación;
stop
@enduml