@startuml CU-MU-005_Modificar_Capacitador
title Diagrama de Actividades - Modificar Información de Capacitador (CU-MU-005)

|#skyblue|Coordinadora de EC|
start
:Inicia gestión de capacitadores;
:Indica capacitador a editar;

|#whitesmoke|Módulo administrativo|
:Provee información actual del capacitador;

|#skyblue|Coordinadora de EC|
:Actualiza la información y confirma;

|#whitesmoke|Módulo administrativo|
:Registra los cambios y confirma actualización;
stop
@enduml